### ISSUE TITLE
[Curseforge] Traveler's Dream page appears to be missing

### ISSUE THREAD

**Issue by IdrisQe** [Darsenia/Traveler-s-Dream#1]
While Thaumic Traveler's Dream is still there, Traveler's Dream is missing. Not sure if you somehow accidentally deleted it, or if Curseforge is being dumb, or what exactly caused this.
![image](https://user-images.githubusercontent.com/40530630/70878940-73597300-1f78-11ea-8526-951ac164959c.png)
![image](https://user-images.githubusercontent.com/40530630/70878986-9e43c700-1f78-11ea-8d6a-2060f30e1d21.png)

**Comment by Darsenia** [comment]
Ha...I changed the description when updating the mod, and lovely curse moderators were resting for almost 3 days and didn't approve changes.All is working now:)
