### ISSUE TITLE
Strange problem with texture colors

### ISSUE THREAD

**Issue by TheLightTwist** [Darsenia/Traveler-s-Dream#4]
Hi! I just found out about your mod, in general it works without complaints, but today I saw a strange bug. Blocks that can change their color depending on the biomes (grass, foliage, vines, soil) sometimes get the wrong color. If you put any block next to such blocks, the colors become correct. Also, this bug is very noticeable when you activate dynamic lighting - if the light source moves, the blocks it illuminates begin to quickly alternate their colors (ie, very quickly become the right or wrong color). If the light source stops, the blocks retain their color at the time of stopping (whether it is correct or not), and the color also becomes correct when installed near any block.
This can best be seen in the screenshot.
I tried to remove all other mods and tried other OTG configurations, but the problem persists and appears only in your mod.
Also, I have tried to enable or disable all installed resourcepacks, this does not affect the problem either.

I'm sorry about the text quality, I used a translator.
![problem](https://user-images.githubusercontent.com/63810245/79489995-d5a8aa00-8024-11ea-99cf-8f86e0930a53.png)

**Comment by Darsenia** [comment]
Hi! That is a known bug, not about Traveler's Dream, but OTG itself.It doesn't happen in otg v6, but happenes in v8+. Me and McPitman, as well as other people, had reported this issue already.I hope that it will be fixed in upcoming OTG releases, as soon as they will be done.
