### ISSUE TITLE
Can't Replant Willow Trees

### ISSUE THREAD

**Issue by gndowns** [Darsenia/Traveler-s-Dream#6]
I spawned in the Silver Willow Isles. I absolutely love this biome but it seems like there's no way to re-plant willow/acacia trees? When I break the leaves they only drop oak saplings, and when I plant those they only grow into regular oak trees.

Are the willow/acacia trees only naturally generated? Is there any way to plant more?

**Comment by Darsenia** [comment]
This is not actually an issue,cause OTG presets can't add any own blocks/items(like leaves or saplings),so leaves are plain vanilla ones.Saplings by default grow in normal vanilla trees, but it is possible (with some OTG knowledge) to change preset's files and make an oak sapling(for example) to grow into custom tree object (only per this biome).
Presets biome files can be found in your /mods folder:
...\mods\OpenTerrainGenerator\worlds\TravelersDreamCompact\WorldBiomes
For Silver Willows  biome files will be Silver Willow Isles.bc and Lake.bc. Near the bottom of the file will be "Sapling Resource" part,it is currently empty. The syntax for this part is described on OTG wiki:

> "OpenTerrainGenerator allows you to grow your custom objects from saplings, instead of the vanilla trees. Add one or more Sapling functions here to override vanilla spawning for that sapling.

The syntax is:

Sapling(SaplingType,TreeType,TreeType_Chance[,Additional_TreeType,Additional_TreeType_Chance.....])

Works like Tree resource instead first parameter.

Sapling types: All, Oak, Redwood, Birch, SmallJungle, BigJungle, RedMushroom, BrownMushroom, Acacia, DarkOak, HugeRedwood All - will make the tree spawn from all saplings, but not from mushrooms. BigJungle - for when 4 jungle saplings grow at once. RedMushroom/BrownMushroom - will only grow when bonemeal is used. "

Tree resources for Silver Willows are:
Tree(10,silverwillow1,10,silverwillow2,10,silverwillow3,10,silverwillow4,10)

So your line will be looking something like this:
Sapling(Oak,silverwillow1,25,silverwillow2,25,silverwillow3,25,silverwillow4,25)
with 25% chance for each tree.

(I hadn't used this for ages, but I hope,that this will work=))

**Comment by gndowns** [comment]
wow thank you!!
