### ISSUE TITLE
Leaves Not Decaying

### ISSUE THREAD

**Issue by SaltSouls** [Darsenia/Traveler-s-Dream#8]
I noticed that the leaves on the trees are set to not decay. This is problematic when using it in conjunction with something like treecapitator as it defeats the purpose of having a mod to make sure trees don't float.

**Comment by Darsenia** [comment]
This is not an issue, undecaying trees and treecapitator usage are described in the preset description.Infortunately, decaying leaves cannot be used(you can use another metadata value for making leaves decaying and forests will not decay, but this will work only until any block update(like building a house in the forest) will happen nearby).I often heard about "safe" usage of other metadata from different people, but experiments failed.
